language: shell

os:
  - linux
  - osx

env:
  jobs:
    - TORCH_VERSION=1.5.0 PYTHON_VERSION=3.7 IDX=cpu

install:
  - source script/conda.sh
  - conda create --yes -n test python="${PYTHON_VERSION}"
  - source activate test
  - conda install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install torch-scatter==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
  - pip install torch-sparse==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
  - pip install torch-cluster==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
  - pip install torch-spline-conv==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
  - pip install torch-geometric
  - pip install codecov
  - pip install sphinx sphinx_rtd_theme
  - pip install .[test]
script:
  - python setup.py test
after_success:
  - codecov
notifications:
    recipients:
      - benedek.rozemberczki@gmail.com
    on_success: always
    on_failure: always

