name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
        
      strategy:
        matrix:
          os: [ubuntu-18.04]

      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7.12
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: 3.7
      - run: conda --version
      - run: which python
      - name: Run installation.
        run: |
         conda install -y scipy
         pip install codecov
         pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
         pip install torchvision==0.8.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
         pip install torch-scatter==2.0.7 -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
         pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
         pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
         pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
         pip install torch-geometric
         pip install codecov
         pip install sphinx sphinx_rtd_theme
         pip install .[test]
         pip install pytest
         python setup.py install
      - name: Install main package
        run: |
          pip install -e .[test]
      - name: Run test-suite
        run: |
          python -m pytest
      - name: Generate coverage report
        if: success()
        run: |
          pip install coverage
          coverage run -m pytest
          coverage xml
      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v1
        if: success()
        with:
          file: coverage.xml
